CREATE SCHEMA IF NOT EXISTS ums
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ums TO PUBLIC;

GRANT ALL ON SCHEMA ums TO postgres;

CREATE TABLE IF NOT EXISTS ums.user_account
(
    id         bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    first_name character varying(16) COLLATE pg_catalog."default"  NOT NULL,
    last_name  character varying(16) COLLATE pg_catalog."default"  NOT NULL,
    password   character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role       character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status     character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username   character varying(16) COLLATE pg_catalog."default"  NOT NULL,
    CONSTRAINT user_account_pkey PRIMARY KEY (id),
    CONSTRAINT uk_castjbvpeeus0r8lbpehiu0e4 UNIQUE (username)
)
    TABLESPACE pg_default;

ALTER TABLE ums.user_account
    OWNER to postgres;